### ISSUE TITLE
Pull OnCore Subjects exposes project id as a search filterable parameter

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_oncore_client#14]
Pull OnCore Subjects exposes project id as a search filterable parameter.  This makes no sense as that page is inherently project-specific. While the Project ID menu is populated, changing the value produces meaningless and blank results.  The Project ID search term should be hidden.

**Comment by tbembersimeao** [comment]
Nice catch @pbchase ! Here is a fix for that - https://github.com/ctsit/redcap_entity/pull/7

**Comment by pbchase** [comment]
Fixed by https://github.com/ctsit/redcap_entity/pull/7
