### ISSUE TITLE
Adding new subject field mappings after already pulling OnCore subjects makes new records instead of updating old ones

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/redcap_oncore_client#21]
Steps to recreate:

1. Create a new project, configure OnCore Client, under Subject Field Mappings, use at least one OnCore variable to populate a REDCap variable
2. Navigate to Pull OnCore Subjects, select any number of subjects and click the Pull OnCore Subjects button
3. Navigate back to the configuration page, select at least one more OnCore variable to populate another REDCap variable and save changes
4. Navigate back to Pull OnCore Subjects, select any number of OnCore subjects which show they need an update, click the Pull OnCore Subjects button again
5. Observe table is now populated with "Not linked" records whose REDCap Record IDs correspond to those of the updated subjects
6. Navigate to Add/Edit Records, observe that "Not linked" records contain all data except that which was just brought in; updated records have been appended to existing records

**Comment by ChemiKyle** [comment]
Update: this does _not_ occur if OnCore's `PrimaryIdentifier` is mapped to REDCap's `record_id`

**Comment by ChemiKyle** [comment]
~Issue is caused in `ExternalModule.php` line 524. The variable `record` is pulled from the `record_id`, if it is not set as OnCore's `PrimaryIdentifier`, it is an integer, and gets incremented.~

Late night epiphany, error just shows up here, but is actually caused by a different function that updates REDCap's records, which is not an database from the entity module.

**Comment by pbchase** [comment]
Addressed in PR #22
