### ISSUE TITLE
REDCap 9.0.1 causes records to not be entered

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/redcap_oncore_client#23]
Upgrading to REDCap 9.0.1 causes a never-ending wait after selecting records and attempting to Pull OnCore Subjects, user can only cancel or leave page and no records are added. However, all `redcap_entity` databases fill as expected.

Also makes the computer running the VM's fan turn on, even after cancelling.

**Comment by ChemiKyle** [comment]
This also affects `9.0.3` in the same way.

`Records::addNewRecordToCache` fails, perhaps this function is deprecated in REDcap 9+. Simply commenting it out leads to normal functionality.

**Comment by ChemiKyle** [comment]
In `/var/www/redcap/redcap_v9.0.x/Classes/Records.php`, the `addNewRecordCache` function gets stuck in an infinite `do` loop because `$project_id` is now a required input variable instead of being determined by `PROJECT_ID`, resulting in a fail to return, and an infinite loop because `$newRecord` is always null.

**Comment by pbchase** [comment]
addressed by pr #24

**Comment by pbchase** [comment]
This error has returned.

**Comment by ChemiKyle** [comment]
Error returns in `8.11.2`, logging shows it is once again hanging on `Records::addNewRecordToCache`. Attempting single records and small groups of records does not cause this hang, but trying to select all in a page does. After attempting to select all on a page, the hanging and heating behavior reappears, but some of the selected records _do_ show up in Add/Edit Records, however adding even individual records hangs after.

UPDATE: it is not individual records, but rather the number of records. After the 18th record has been pulled in, the issue appears on an attempt to add a 20th.

**Comment by pbchase** [comment]
Not reproducible in 9.0.1
