### ISSUE TITLE
Cannot create a second record...

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_oncore_client#31]
Cannot create a second record if OnCore's PrimaryIdentifier is not mapped to REDCap's record_id

**Comment by ChemiKyle** [comment]
@pbchase did this occur in 8.11.2? I didn't see this behavior while working on the reappearance of issue #23

**Comment by pbchase** [comment]
Yes, I experienced this with 8.11.2

**Comment by pbchase** [comment]
Will not fix. setting min redcap version to 9.0.1 in release 2.2.0
