### ISSUE TITLE
Add support for OnCore fields "Subject ID" and SequenceNumber

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_oncore_client#37]
OnCore provides two fields that might be of interest to study teams: "Subject ID" and SequenceNumber. These should be added to the interface.  SequenceNumber is especially important. See [Harshita's Research](https://github.com/ctsit/redcap_oncore_client/files/3444324/harshitas_research.pdf) for detail.

**Comment by pbchase** [comment]
SequenceNumber added by PR #38. Let's not implement "Subject ID" as it seems much less useful.

**Comment by ChemiKyle** [comment]
@pbchase A field meant for Subject ID was left in the `config.json` file as `id` in PR #38.  
https://github.com/ctsit/redcap_oncore_client/blob/910f946f8e6f0b9137b3f3f69233975934efce08/config.json#L321-L325  
Can lines of a commit be cherry-"plucked" or should I open a new PR to remove it?
