### ISSUE TITLE
Curious data diff problem

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_oncore_client#39]
@ChemiKyle, I got a weird synch problem in my Oncore client testing today. Testing with Protocol OCR20388 in the https://oncore-test.ahc.ufl.edu host, one record would not synchronize right. 

```
mysql> select * from redcap_entity_oncore_subject_diff;
+----+------------+------------+------------+-----------+------------+--------------+-------------+-----------+----------+---------------------------------+
| id | created    | updated    | subject_id | record_id | project_id | subject_name | subject_dob | type      | status   | diff                            |
+----+------------+------------+------------+-----------+------------+--------------+-------------+-----------+----------+---------------------------------+
| 75 | 1565000765 | 1565000765 |        200 | 989       |         14 | Pup Pluto    | -1406577600 | data_diff | on_study | {"LastName":["Pluto","Pluto "]} |
+----+------------+------------+------------+-----------+------------+--------------+-------------+-----------+----------+---------------------------------+
```

The problem is a trailing space on the `LastName` field. We must be trimming the data before we write it. We need to not trim it. We need to honor whatever garbage they offer us. :-)

**Comment by ChemiKyle** [comment]
Strangely, removing the `trim`'ing of fields does not resolve this issue.

UPDATE:  
Unfortunately this error is due to the REDCap core function `Records::saveData`.   
https://github.com/ctsit/redcap_oncore_client/blob/47aece2801637d10763c5345d84d546c75e8541f/classes/entity/SubjectDiff.php#L69  
Fields and values are trimmed there. To get rid of this error we will have to either recreate that function's operations without trimming or similarly trim incoming OnCore data.

**Comment by pbchase** [comment]
So you're saying `Records::saveData` trims data? If that is the case, we'll need to trim the OnCore source data as well before we cache it. I hate doing that, but we need this data to fit in the REDCap ecosystem. If we start saving untrimmed data we'll get into trouble later.

**Comment by ChemiKyle** [comment]
Yes, unfortunately: `redcap_v9.1.1/Classes/Records.php` lines `4455`/`4572`.  
Manual entry via GUI in Add/Edit Records allows spaces in fields though - I will look there for an alternate function before implementing more trimming.

UPDATE:  
`ProjectGeneral/form_renderer_functions.php` is where the `saveRecord` function that Add/Edit Records uses is found. Unfortunately it is heavily coupled to the form; the only argument it takes is the proposed `record_id`, the rest is  `$_POST` data from the form used to fill in SQL statements.  
Trim it is.
