### ISSUE TITLE
OnCore client can only see open protocols

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_oncore_client#9]
The OnCore client only sees open protocols. In using the SIP URL, the OnCore client is only seeing protocols that are open to accrual. REDCap project builders using this module would be unable to configure their project before accrual starts. We need an alternative way to enumerate the protocols.

As the protocol numbers are sequential, we could allow the specification of some combination of naming pattern, base name, and starting number that would allow the ONCore client to guess protocol numbers. E.g., it could start at number 00042, using a prefix of "OCR-", to query for OCR-00042, OCR-00043, etc. until it could not locate OCR-NNNNN at which point it would stop assuming it had reached the highest allocated protocol ID. 

With these guessed protocol IDs, the OnCore client can query the WSDL interface to get full details about the protocol and its enrollment. It can use a limited set of this data to populate the "select protocol" drop down.

**Comment by pbchase** [comment]
Harshita and Joe said guessing at sequential protocol IDs was a bad idea. UF is rare in its use of sequenced protocol IDs. What's more, even UF has gaps in its sequence. They have proposed to write a small web services interface to allow enumeration of all protocol IDs. With those IDs, we can query OnCore's standard WSDL interface for the protocol details. 

This change means we will have to implement this new web-services interface, but it will be inexpensive to implement. More significant is that we will create a dependency on a non-standard OnCore add-on.  We will want to encourage UF's OCR to open source the code and publish it on Github or some such. They might need help with that effort. 

We should leave the existing SIP URI-based protocol lookups in place to allow sites that have not implemented the UF WS interface to the OnCore client in a more limited fashion. The choice of protocol lookup methods should be configurable at the global level.

**Comment by pbchase** [comment]
@ChemiKyle, I believe Harshita has implemented this web service in OCR's OnCore test instance.  Could you contact her to verify that and get guidance how to write the client end of this feature? 

With that information, write this new client component and make it an optional method of looking up the list of Protocols. Add the configuration field for this System-wide level. 

Be aware that this new feature might allow the selection of protocols that are not queriable via other API methods we need to call. Specifically, these protocols are not yet open to enrollment. We would expect them to have no enrollees. Test other interfaces for normal behavior when this feature is activated.

**Comment by ChemiKyle** [comment]
Harshita responded, she did develop this functionality and is working on setting it up in a docker container and will let me know when she has it deployed in test.

**Comment by ChemiKyle** [comment]
Harshita just let me know their API is up, I confirmed it's working with a short Python script. I'll start integrating it into the module.

**Comment by ChemiKyle** [comment]
Resolved by addition of optional API in #25, completed in #26
